/** Entidades y comercios que colaboran con la asociación (de la web antigua). */
export const collaborators = [
  "CaixaBank",
  "Ajuntament de Sant Cugat",
  "Fundació CMJ Godó",
  "PortAventura World",
  "L'Aquàrium de Barcelona",
  "Museu de la Xocolata",
  "Barceló Hotels",
  "ISDIN",
  "Aura Fundació",
  "Fundació ASPASIM",
  "Clínica Maristany",
  "Club Tennis Natació Sant Cugat",
  "Hípica Can Caldés",
  "Sant Cugat Sports",
  "FC Padel",
  "Tot Sant Cugat",
  "Cugat.cat",
  "Reactivos para Diagnóstico",
  "Biolord",
  "BenuSalud",
  "Farmàcia Beringues",
  "Opticalia",
  "Cabreiroa",
  "Grand Fontaine",
  "Roqueta Origen",
  "Fruit Santonia",
  "Gelats Pros",
  "Pastisseria Sàbat",
  "Goiko",
  "Garden Pizza",
  "La Pasta Boixa",
  "Vulcano Restaurant",
  "New Catering",
  "Cafeteria Silvia",
  "Marcal Cafeteria Restaurante",
  "Maison du Savon de Marseille",
  "French Kiss Beauty",
  "Siluet Gym y Estetic",
  "Tintoreria Sant Cugat",
  "Mariola Joiers",
  "Uniformes Prat",
  "Calipage",
  "Boxley",
  "Moooi",
  "Moon",
  "Grupfiro",
  "Biopompas",
  "Miquel Biosca Fotografia",
  "Dave Dans",
  "Jordi Coromina",
  "Vicente López Figuerás",
] as const;
